[package]

name = "lru-cache"
version = "0.1.1"
license = "MIT/Apache-2.0"
description = "A cache that holds a limited number of key-value pairs"
authors = [
    "Stepan Koltsov <stepan.koltsov@gmail.com>",
]

repository = "https://github.com/contain-rs/lru-cache"
homepage = "https://github.com/contain-rs/lru-cache"
documentation = "https://contain-rs.github.io/lru-cache/lru_cache"
keywords = ["data-structures"]
readme = "README.md"

[features]
heapsize_impl = ["heapsize", "linked-hash-map/heapsize_impl"]

[dependencies]
linked-hash-map = { git = "https://github.com/koivunej/linked-hash-map", branch = "mark_lru" } # "0.4.2"

heapsize = { version = "0.3.9", optional = true }
